#!/bin/bash

APP_NAME="TrainTime"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Check if monkeyc exists
if ! command -v monkeyc &> /dev/null; then
    echo "Error: monkeyc not found. Please run ./setup.sh and install the SDK first."
    exit 1
fi

if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    echo "Usage: ./build.sh [command]"
    echo ""
    echo "Commands:"
    echo "  (none)              Build for fenix6pro (default device)"
    echo "  <device>            Build for a specific device (e.g. fenix7pro)"
    echo "  release             Build .iq package for all devices (version from manifest.xml)"
    echo ""
    echo "Examples:"
    echo "  ./build.sh                  Build debug .prg for fenix6pro"
    echo "  ./build.sh epix2pro47mm     Build debug .prg for epix2pro47mm"
    echo "  ./build.sh release          Build release .iq for all devices"
    exit 0
fi

cd "$SCRIPT_DIR/$APP_NAME"

# Generate Version.mc from manifest version
VERSION=$(grep -oP 'iq:application.*version="\K[^"]+' manifest.xml)
cat > source/Version.mc <<VERSION_EOF
// Auto-generated by build.sh — do not edit manually
module AppVersion {
    const VERSION = "$VERSION";
}
VERSION_EOF

# Ensure Secrets.mc exists
SECRETS_FILE="source/Secrets.mc"
if [ ! -f "$SECRETS_FILE" ]; then
  if [ -n "${TRAINTIME_API_KEY:-}" ]; then
    echo "Generating $SECRETS_FILE from TRAINTIME_API_KEY env var..."
    cat > "$SECRETS_FILE" <<SECRETS_EOF
module Secrets {
    const API_KEY = "$TRAINTIME_API_KEY";
}
SECRETS_EOF
  else
    echo "Error: $SECRETS_FILE not found."
    echo ""
    echo "Either:"
    echo "  1. Copy from example:  cp $SECRETS_FILE.example $SECRETS_FILE"
    echo "     and replace YOUR_API_KEY_HERE with your actual key"
    echo "  2. Set env var:  TRAINTIME_API_KEY=your_key ./build.sh"
    exit 1
  fi
fi

# Validate API key
SECRETS_PATH="$(pwd)/$SECRETS_FILE"
KEY=$(grep -oP "API_KEY = \"\K[^\"]+" "$SECRETS_FILE")
if [ -z "$KEY" ] || [ "$KEY" = "YOUR_API_KEY_HERE" ]; then
  echo "Error: API key in $SECRETS_PATH is not set."
  echo "Replace YOUR_API_KEY_HERE with your actual key."
  exit 1
fi

echo "API key: ${KEY:0:8}... ($SECRETS_PATH)"

HTTP_CODE=$(curl -s -o /dev/null -w '%{http_code}' -H "X-API-Key: $KEY" "https://api.traintime.ch/v1/departures?id=8503000&limit=1")
if [ "$HTTP_CODE" = "200" ]; then
  echo "API key verified OK"
else
  echo "Error: API key check failed (HTTP $HTTP_CODE)"
  echo "Check your key in $SECRETS_PATH"
  exit 1
fi

if [ "$1" = "release" ]; then
    VERSION=$(grep -oP 'iq:application.*version="\K[^"]+' manifest.xml)
    echo "Version: $VERSION (from manifest.xml)"

    echo "Building $APP_NAME release package for all devices..."
    monkeyc -e -f monkey.jungle -o ../$APP_NAME.iq -y ~/.Garmin/developer_key.der -r

    if [ $? -eq 0 ]; then
        echo "Release build successful! Output: $APP_NAME.iq"
        echo ""
        echo "Upload $APP_NAME.iq to the Garmin Connect IQ Store."
        echo "App Version: $VERSION"
    else
        echo "Release build failed!"
        exit 1
    fi
else
    DEVICE="${1:-fenix6pro}"
    VERSION=$(grep -oP 'iq:application.*version="\K[^"]+' manifest.xml)
    echo "Building $APP_NAME v$VERSION for $DEVICE..."
    monkeyc -d $DEVICE -f monkey.jungle -o ../$APP_NAME.prg -y ~/.Garmin/developer_key.der

    if [ $? -eq 0 ]; then
        echo "Build successful! Output: $APP_NAME.prg (v$VERSION)"
    else
        echo "Build failed!"
        exit 1
    fi
fi
